databases:
  - name: lovaseball_db
    databaseName: lovaseball_db
    user: lovaseball
    region: singapore

services:
  - type: web
    name: lovaseball
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lovaseball
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

